# pyproject.toml.template
[project]
name = "${PROJECT_NAME}"
version = "${PROJECT_VERSION}"
description = "${PROJECT_DESCRIPTION}"
authors = [
    { name = "${AUTHOR_NAME}", email = "${AUTHOR_EMAIL}" },
]

readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"

# Build System
[build-system]
requires = [
  "setuptools>=73.0.0", 
  "wheel"
]

# Dependencies
dependencies = [
    "python-dotenv>=1.0.1",
    "rich",
]
[project.optional-dependencies]
dev = [
    "black",
    "ruff",
]
[dependency-groups]
dev = [
    "mypy",
    "pytest",
]

# Tools
[tool.setuptools]

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
